from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("compose/<str:page>", views.compose, name="compose"),
    path("comments/<str:view>/<int:page_id>/<int:page_nr>", views.comments, name="comments"),
    path("like/<int:id>", views.like, name="like"),
    path("dislike/<int:id>", views.dislike, name="dislike"),
    path("editcomments/<int:id>", views.edit_comments, name="editcomments"),
    path("novels/<str:order>/<int:page_nr>", views.novels_view, name="novels"),
    path("chapters/<int:id>/<int:page_nr>", views.chapters_view, name="chapters"),
    path("novel/<int:id>", views.novel, name="novel"),
    path("chapter/<int:id>", views.chapter, name="chapter"),
    path("search/<int:page_nr>", views.search, name="search"),
    path("reply/<int:id>", views.reply, name="reply"),
    path("bookmark/<int:id>", views.bookmark, name="bookmark"),
    path("create_novel", views.create_novel, name="create_novel"),
    path("create_chapter/<int:id>", views.create_chapter, name="create_chapter"),
    path("profile/<str:username>", views.profile, name="profile"),
    path("edit_profile", views.edit_profile, name="edit_profile"),
    path("bookmarks", views.bookmarks, name="bookmarks"),
    path("follow/<str:username>", views.follow, name="follow" ),
    path("delete/<str:view>/<int:id>", views.delete, name="delete"),
    path("edit_novel/<int:id>", views.edit_novel, name="edit_novel"),
    path("edit_chapter/<int:id>", views.edit_chapter, name="edit_chapter"),
    path("rating/<int:id>", views.rating, name="rating"),
]   
