# Generated by Django 5.1.7 on 2025-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0002_novel_image_alter_novel_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.TextField(),
        ),
    ]
