# Generated by Django 5.2.6 on 2025-10-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_remove_novel_image_comment_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmark_by', to='novel.novel'),
        ),
    ]
