# Generated by Django 5.2.6 on 2025-10-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0009_alter_message_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="message_recieved",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
