# Generated by Django 5.2.6 on 2025-10-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0010_remove_message_recipient_message_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replys",
                to="novel.message",
            ),
        ),
    ]
