# Generated by Django 5.2.6 on 2025-10-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0012_alter_message_parent_message_alter_message_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
    ]
