# Generated by Django 5.2.6 on 2025-10-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0013_remove_user_followers"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
