# Generated by Django 5.2.6 on 2025-10-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0014_novel_views_alter_chapter_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
