# Generated by Django 6.0.1 on 2026-01-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0015_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='fanfic_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='last_chapter_scraped',
            field=models.TextField(blank=True, null=True),
        ),
    ]
