# Generated by Django 6.0.1 on 2026-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0016_novel_fanfic_id_novel_last_chapter_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='ao3_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
