# Generated by Django 6.0.1 on 2026-04-20 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0018_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookmarks',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.chapter'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='novel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.novel'),
        ),
    ]
