# Generated by Django 6.0.1 on 2026-04-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0019_alter_chapter_options_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
