# Generated by Django 6.0.1 on 2026-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0020_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='creator',
            field=models.CharField(blank=True, default='Admin', null=True),
        ),
    ]
